# Generated by Django 4.2.13 on 2026-06-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorrequest',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='request_files/'),
        ),
    ]
