# Generated by Django 4.2.13 on 2026-06-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_supervisionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
